version: '2'
services:
    corecm-app:
        image: corecm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://corecm-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    corecm-mssql:
        extends:
            file: mssql.yml
            service: corecm-mssql
